### ISSUE TITLE
Upload solutions on the next day

### ISSUE THREAD

**Issue by faizankshaikh** [tamycova/30DaysHR#2]
Give atleast a days chance for the people to solve the problems. It would not be fair if anyone got the solutions here easily.

Anyways, keep up the good work!

**Comment by tamycova** [comment]
I thought about it! But this challenge is meant as a self training/learning more than a competition, it wouldn’t help anyone trying to learn to look for the solution, they would be cheating on themselves!

**Comment by faizankshaikh** [comment]
Good point.:+1:  There's another thing. Please put individual language codes in their respective folder. It would make the repo clean.

**Comment by tamycova** [comment]
I did! thanks
