### ISSUE TITLE
Java folders and New owner

### ISSUE THREAD

**Issue by tamycova** [tamycova/30DaysHR#64]
Hi guys! 
1. For Java developers, should we add folders for specific java versions? @upa8 
2. Ill be hiking with no signal for 10 days, we need 1 or 2 volunteers to review the pull requests and merges to the main branch!!!

**Comment by upa8** [comment]
Yes , sure . It will be my pleasure @tamycova . Add me as a collaborator so that I can merge if I find any pull request about Java :) .

**Comment by tamycova** [comment]
thanks! anyone else for collaborator?

**Comment by tamycova** [comment]
@della-90 ? :dancer:

**Comment by della-90** [comment]
Yup, I can try to help @upa8 in pull requests handling :)

**Comment by DinerIsmail** [comment]
@upa8, can you also please remove the badly named 'Day10.' and 'Day10' files in the Java folder? For some reason I can't do it myself, and I get some errors when trying to commit my changes

**Comment by upa8** [comment]
Yes , sure ... Give me some time .

**Comment by tamycova** [comment]
thanks a lot @della-90 :)

**Comment by della-90** [comment]
You're welcome :)
